azure-face-api-registrator-python-kube:
  startup: yes
  always: yes
  scale: 1
  env:
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/xxxxxxxx
    QUEUE_ORIGIN: azure-face-api-registrator-python-kube-queue
    QUEUE_TO: register-face-to-guest-table-kube-queue