azure-face-api-registrator-kube:
  startup: yes
  always: yes
  scale: 1
  env:
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/xxxxxxxx
    QUEUE_FROM: azure-face-api-registrator-kube-queue
    QUEUE_TO: register-face-to-guest-table-kube-queue